
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://ananda1066.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Alisha Nanda"
title: "Alisha Nanda"
description: "Personal website of Alisha Nanda"
keywords: "nanda, alisha, personal"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: ""

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Motivated."
  - text: "Team Member."
  - text: "Passionate."
  - text: "Inventive."
  - text: "Leader."
  - text: "Ambitious."
  - text: "Hard Worker."
  - text: "Persistent."
  - text: "Diligent."
  - text: "Dependable."

me-img: "/img/linkedinPic.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/100007959578642/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

#enable-gesture-navigation: True

#post-preview-words: 96

#paginate: 5

#email-share: True
#fb-share: True
#twitter-share: True
#linkedin-share: True
#reddit-share: True
#google-plus-share: True
#tumblr-share: True
#pinterest-share: True
#pocket-share: True
#vkontakte-share: True

#disqus-shortname: "panossakkos"

#syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ghc.png"
    date: "Oct 2017: Grace Hopper Conference"
    description: "GHC Scholar to attend 2017 Conference in Florida. Will learn about female involvement in computer science and listen to empowering women discuss their experiences."
  - image: "/img/timeline/kodethon.png"
    date: "Oct 2016 - Present: Undergraduate Research Assistant"
    description: "Under Professor Su. Working on Ruby on Rails app that automatically generates programming questions. Focusing on views and controllers for topics."
  - image: "/img/timeline/hackdavis.png"
    date: "May 2017 - Present: HackDavis Organizing Team"
    description: "Accepted as member of External Affairs team for HackDavis 2018. Organizing transportation, networking with nonprofits/clubs, outreach."
  - image: "/img/timeline/dcsc.png"
    date: "May 2017 - Present: Davis Computer Science Club"
    description: "Elected pragmatic programming chair of DCSC. Hosts events for the club and suggests new ideas, such as female-centered events and a year-long hackathon project."
  - image: "/img/timeline/ucdavis.png"
    date: "Jan 2017 - April 2017: Research Assistant"
    description: "Under Professor Ghiasi. Worked on Android app that measured oxygen/carbon dioxide levels to detect signs of lung cancer. Learned some hardware basics."
  - image: "/img/timeline/hshacks.jpg"
    date: "March 2017: HSHacks Mentor"
    description: "Mentored at HSHacks, hackathon for high-schoolers. Helped students with projects and held an impromptu Android development course for a few attendees."
  - image: "/img/timeline/xxhacks.png"
    date: "Feb 2017: Speaker at XXHacks"
    description: "Spoke on a panel at XXHacks, all-female hackathon. Talked about my experiences in the field as a female, mainly in building my startup and in my classes."
  - image: "/img/timeline/tilewarpicon.png"
    date: "Jan 2015 - Sep 2016: TileWarp"
    description: "Startup formed around Android app by same name (see Projects). Organized meeting times, met with users, featured in school newspaper."
  - image: "/img/timeline/autoforce.jpg"
    date: "July 2015 - Aug 2015: Auto Force"
    description: "Marketed for startup, focusing on social media. Increased Facebook likes by over 20% in three weeks."   
  - image: "/img/timeline/gtgtclogo.png"
    date: "April 2013: Stanford Girls Teaching Girls To Code Camp"
    description: "Stanford CS students taught Scratch/Python/Arduino. Explored the underwhelming female involvement in the field. Inspired me through empowering talks/leaders."

# First image of the Timeline

timeline-img: "/img/timeline/timelinepic.jpg"

###########
# Contact #
###########

email: "ananda@ucdavis.edu"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/alisha.nanda.96"
  - title: "twitter"
    url: "https://twitter.com/alisha98765"
  - title: "github"
    url: "https://github.com/ananda1066"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/alishananda/"
  #- title: "bitcoin"
   # url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  #- title: "rss"
  #  url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Projects: 'projects'
  Experience: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
